---
deployment:
  tasks:
    - export DEPLOYPATH=/home/spotigra/public_html # Replace this with the path to your cPanel public_html directory

    # Build the project
    - npm install
    - npm run build

    # Clean the cPanel directory
    - rm -rf $DEPLOYPATH/*

    # Copy the built project to cPanel public_html
    - cp -R dist/* $DEPLOYPATH

    # Add any additional commands you need to run after the deployment.
    # For example, you might want to run database migrations, etc.
